### PR TITLE
Fix mc player edit resource error

### LINKED ISSUE #569: Admin user edit Illuminate\View\ViewException
Sentry Issue: [PCB-WEB-B6](https://sentry.io/organizations/projectcitybuild/issues/3269471085/?referrer=github_integration)

```
BadMethodCallException: Call to undefined method Entities\Models\Eloquent\Account::toResource()
  File "/storage/framework/views/5a97f40fc43251130b6724a0f9498e235deb40b2.php", line 20, in require
    <option value="<?php echo e($minecraftPlayer->account_id); ?>" selected data-data='<?php echo json_encode($minecraftPlayer->account->toResource(), 15, 512) ?>'></option>
  File "/app/Http/Middleware/RequiresMfaEnabled.php", line 16, in App\Http\Middleware\RequiresMfaEnabled::handle
    return $next($request);
  File "/app/Http/Middleware/MfaGate.php", line 40, in App\Http\Middleware\MfaGate::handle
    return $next($request);
  File "/app/Http/Middleware/PanelAccess.php", line 21, in App\Http\Middleware\PanelAccess::handle
    return $next($request);
  File "/public/index.php", line 57
    $request = Illuminate\Http\Request::capture()
...
(62 additional frame(s) were not displayed)

Illuminate\View\ViewException: Call to undefined method Entities\Models\Eloquent\Account::toResource() (View: /var/www/projectcitybuild.com/resources/views/admin/minecraft-player/edit.blade.php)
  File "/app/Http/Middleware/RequiresMfaEnabled.php", line 16, in App\Http\Middleware\RequiresMfaEnabled::handle
    return $next($request);
  File "/app/Http/Middleware/MfaGate.php", line 40, in App\Http\Middleware\MfaGate::handle
    return $next($request);
  File "/app/Http/Middleware/PanelAccess.php", line 21, in App\Http\Middleware\PanelAccess::handle
    return $next($request);
  File "/public/index.php", line 57
    $request = Illuminate\Http\Request::capture()
...
(57 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by freddyheppell**
## Overview of Changes
* Fixes error caused by using `->toResource()` function (fixes #569)

## Deployment Requirements
- [ ] Composer update
- [ ] NPM update
- [ ] Database migration
- [ ] .env update
- [ ] Environment upgrade (eg. PHP version)
- [ ] Other (please specify)

### CODE REVIEW

**Review by andyksaw — APPROVED** [review]
LGTM! Although I wonder why we're using `Resources` at all inside the views 🤔

**Comment by freddyheppell** [comment]
It's because to select and entry in a Selectize box you have to give it the exact JSON object it gets to populate the element, which in this case is a resource collection. I suppose we could refactor into a component though?

**Comment by andyksaw** [comment]
Ah right. I think Selectize is actually busted at the moment, and it's depending on a package that has security vulnerabilities (and we can't update it), so probably best to refactor that later

**Comment by freddyheppell** [comment]
Will look into alternatives (select2 comes to mind but there may be others)

**Pull request merged**
